name: build and push image

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  IMAGE_NAME: "jellyfin-with-ytdlp"
  PLATFORM_LIST: "linux/amd64,linux/arm/v7,linux/arm64/v8"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: ${{ env.PLATFORM_LIST }}

      - name: build the image
        run: |
          docker buildx build \
          --build-arg PG_VERSION=${{ env.IMAGE_TAG }} \
          --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest \
          --platform ${{ env.PLATFORM_LIST }} \
          --push \
          .
